language: java
install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
- build
- publish

jobs:
  include:
  - stage: build
    if: branch IS present AND tag IS blank
    script: ./gradlew build
  - stage: publish
    if: tag IS present
    script: ./gradlew -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET publishPlugins
