/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package in.co.rahogata.swayamjar

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'in.co.rahogata.swayamjar.greeting' plugin.
 */
public class SwayamjarPluginFunctionalTest extends Specification {
    def "can run task"() {
        given:
        def projectDir = new File("build/functionalTest")
		def sourceFile = new File("src/test/resources/Main.jar").absolutePath.replace("\\", "\\\\")
		def destFile = new File("build/libs/Main.jar").absolutePath.replace("\\", "\\\\")
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle").text = ""
        new File(projectDir, "build.gradle").text = """
            plugins {
                id('in.co.rahogata.swayamjar')
            }
			
			swayamJar {
				source = file('${sourceFile}')
				destination = file('${destFile}')
				osPlatforms = ['nix', 'WINDOWS']
			}
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
		runner.withArguments("swayamJar")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("BUILD SUCCESSFUL") && new File(destFile.take(destFile.lastIndexOf('.')) + ".bat").exists() && new File(destFile.take(destFile.lastIndexOf('.'))).exists() 
    }
}
